### ISSUE TITLE
Fix HLS convolutions to correctly use pooling dimensions.

### ISSUE THREAD

**Issue by yarnellr** [FedericoSerafini/HLS-CNN#3]
Update HLS convolution logic within each pooling area to correctly use the pooling dimensions, not the kernel dimensions minus one.

**Comment by FedericoSerafini** [comment]
Hi,

If you are you referring to the strange loops in 05-Vitis-HLS/conv.cc,
I try to explain my point of view below.

At the moment, let's forget the number of parallel convolutions (8) that we are using an let's reason
with just one convolutional layer followed by a pooling layer.
The pooling layer reads, one single data at a time, the results produced by the
convolutional layer from the stream.
The order of the data that the pooling layer expects is the obvious one, e.g.:
given a 2x2 pooling area, the firt sequence of data that the pooling layer wants to receive is the following:
(0,0)(0,1)
(1,0)(1,1),
where (i, j) is the data in position i, j of the feature image produced by the convolutional layer.

The next sequence of data that the pooling layer expects is the following:
(0,2)(0,3)
(1,2)(1,3),
and so on...

A stream is a one-dimensional object, so we need to flat all the 2x2 matrices (that together compose the
feature image) into a vector like the following (0,0)(0,1)(1,0) (1,1) (0,2)(0,3)(1,2)(1,3)(0,4)....
and the feed such vector into the stream, from the left to the right.
This is the reason behind the strange loops in the 05-Vitis/conv.cc.

Are you still convinced about the use of pooling area size instead of the kernel size - 1?
We wrote the code a while ago so I could be wrong...
One fact that makes me think I am right is that co-simulation works.

Regards,
Federico

**Comment by yarnellr** [comment]
Federico,

Thank you for writing and for your detailed explanation! Within the conv.cc, my understanding of the loops is as follows:

The outer two loops (r and c) loop over all the pooling regions.

The middle two loops (wr and wc) loop over all pixels in the pooling region selected above.

The inner two loops (kr and kc) loop over all filters for each pixel selected above.

The issue is that the middle loops run (KRN_ROWS - 1) and (KRN_COLS - 1) times. Since the intention of these loops is to cover all pixels within each pooling region, they need to run POOL_ROWS and POOL_COLS times.

As you pointed out, it does work as is because KRN_ROWS - 1 happens to equal POOL_ROWS, and KRN_ COLS - 1 = POOL_COLS. So the correct value happens to be used by chance.

However, if you change POOL_ROWS and COLS to (let’s say) 4, things break down, and the simulation fails. I will attach what I believe to be an appropriate fix. If you want to make me a contributor, I can push it, or you are of course welcome to do as you like with the file yourself.

Thanks again for providing such an excellent reference project. It was very well done and has helped me tremendously to learn for my doctoral research.


-Rich

**Comment by FedericoSerafini** [comment]
Hello Rich,

We are really glad to hear that our project has been useful!

I cannot see the attachment, maybe you forgot it?

**Comment by yarnellr** [comment]
Sorry about that. I see the attachment on my end, but my computer has been known to do strange things with attachments. I will paste below the original and updated portions of the code from conv.cc.

Original:
      win_for_rows:
      for (int wr = 0; wr < KRN_ROWS-1; ++wr)
      {
        win_for_cols:
        for (int wc = 0; wc < KRN_COLS-1; ++wc)
        {

Updated:
      win_for_rows:
      for (int wr = 0; wr < POOL_ROWS; ++wr)
      {
        win_for_cols:
        for (int wc = 0; wc < POOL_COLS; ++wc)
        {


On Nov 17, 2023, at 7:57 AM, Federico Serafini ***@***.***> wrote:



Hello Rich,

We are really glad to hear that our project has been useful!

I cannot see the attachment, maybe you forgot it?

**Comment by giacomoboldini** [comment]
Hello Rich,

I just checked what you were saying and you are right about this problem: HLS breaks down and simulations fail when the pool size is different from the (current) size of 2. Thank you very much for finding the problem and proposing this solution. 

If you are okay with that (and you are familiar with them), you can create a pull request to solve the problem, and we will approve it. In this case, we will be grateful if you can follow these suggestions of ours:
- after fork the repository, commit the changes to a new branch with a meaningful name (say "fix-hls-conv-for") and create the pull-request to merge with the main branch;
- link the pull request with this issue;
- use meaningful labels and variable names for the loops involved: _win_for_rows_ and _win_for_cols_ should be replaced with _pool_for_rows_ and _pool_for_cols_, respectively, and _wr_ and _wc_ should be replaced with _pr_ and _pc_, respectively;
- add comments to this section of code, referring to what you said in this topic:
  > The two outer loops (r and c) loop over all pooling regions. 
  > The two middle loops (pr and pc) loop over all pixels in the previously selected pooling region.
  > The two inner loops (kr and kc) loop over all filters for each previously selected pixel.

Let us know if you're ok with that. Thank you. 

Giacomo

**Comment by yarnellr** [comment]
Sounds good! Will do. I’m on holiday right now, so it might be a week or more, but I will take care of it.

-Rich

On Nov 18, 2023, at 2:00 PM, Giacomo Boldini ***@***.***> wrote:

﻿

Hello Rich,

I just checked what you were saying and you are right about this problem: HLS breaks down and simulations fail when the pool size is different from the (current) size of 2. Thank you very much for finding the problem and proposing this solution.

If you are okay with that (and you are familiar with them), you can create a pull request to solve the problem, and we will approve it. In this case, we will be grateful if you can follow these suggestions of ours:

  *   after fork the repository, commit the changes to a new branch with a meaningful name (say "fix-hls-conv-for") and create the pull-request to merge with the main branch;
  *   link the pull request with this issue;
  *   use meaningful labels and variable names for the loops involved: win_for_rows and win_for_cols should be replaced with pool_for_rows and pool_for_cols, respectively, and wr and wc should be replaced with pr and pc, respectively;
  *   add comments to this section of code, referring to what you said in this topic:

The two outer loops (r and c) loop over all pooling regions.
The two middle loops (pr and pc) loop over all pixels in the previously selected pooling region.
The two inner loops (kr and kc) loop over all filters for each previously selected pixel.

Let us know if you're ok with that. Thank you.

Giacomo

**Comment by yarnellr** [comment]
I went to push my update today, but got the following message. Can you check my permissions and advise please? I can pull, so I know I have read privileges. I just can't push.

% git push origin fix-hls-conv-pool-loop
ERROR: Permission to FedericoSerafini/HLS-CNN.git denied to yarnellr.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights and the repository exists.

**Comment by FedericoSerafini** [comment]
Hello Rich,

I created a new branch "fix-hls-convolution" that should be somehow linked to this issue.
I think you should send a "pull request" to that branch and it will be automatically linked to this issue.

**Comment by yarnellr** [comment]
I still get the error below. My understanding is that I need to push my committed changes, then do the pull request.

% git push origin fix-hls-convolution
ERROR: Permission to FedericoSerafini/HLS-CNN.git denied to yarnellr.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights and the repository exists.

**Comment by giacomoboldini** [comment]
Observing the errors that you encountered, I suppose that you may have cloned our repository instead of forking. Is my assumption correct?

Here, I've outlined the steps for forking and creating a pull request:

1. **Fork the Repository:**
   - Navigate to the [repository](https://github.com/FedericoSerafini/HLS-CNN).
   - Click on the "Fork" button in the upper right corner of the GitHub interface to create your fork.
   - This creates a copy of the repository in your GitHub account.

2. **Clone Your Fork:**
   - Copy the HTTPS/SSH link of your fork from the "Code" button on the GitHub interface.
   - Clone your forked repository to your local machine using the following command:
     ```bash
     git clone <previous-link-of-repository>
     ```
   - Alternatively, you can download the repository as a zip file by clicking on the "Code" button and selecting "Download ZIP."

3. **Keep Your Fork Updated (Optional):**
   - To synchronize your fork with the original repository, add the upstream remote:
     ```bash
     git remote add upstream <previous-link-of-repository>
     ```

   - Fetch changes from the upstream repository and merge them into your local branch:
     ```bash
     git fetch upstream
     git merge upstream/main
     ```

   - Push the updated changes to your fork:
     ```bash
     git push origin main
     ```

  For detailed instructions on steps **1**, **2** and **3**, you can refer to the [GitHub Forking Guide](https://docs.github.com/en/get-started/quickstart/fork-a-repo). 

4. **Create a Feature Branch:**
   - Create a new branch for your feature with a meaningful name:
     ```bash
     git checkout -b feature-branch-name
     ```

5. **Implement Your Changes:**
   - Make the necessary modifications and additions in your feature branch.

6. **Commit Your Changes:**
   - Stage and commit your changes with clear, concise commit messages:
     ```bash
     git add .
     git commit -m "Brief description of changes"
     ```

7. **Push Changes to Your Fork:**
   - Push your changes to your fork on GitHub:
     ```bash
     git push origin feature-branch-name
     ```

8. **Create a Pull Request:**
   - Visit the [original repository](https://github.com/FedericoSerafini/HLS-CNN).
   - Click on the "New Pull Request" button.
   - Ensure that the base repository and base branch are set to the correct values.
   - Write a detailed description of your changes in the pull request.
   - Click on "Create Pull Request" to submit your changes for review.
   
  For detailed information on creating and managing pull requests, you can refer to the [GitHub Guide: Creating a pull request from a fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork).

I hope these instructions have been clear and helpful. If you encounter any issues or have questions about these steps, please don't hesitate to contact us via email. 

Thank you,

Giacomo

**Comment by yarnellr** [comment]
Thanks for the instructions! This was my first time using git this way. I submitted the pull request. I assume you need to approve it to close it out. Let me know if you need anything else.

**Comment by FedericoSerafini** [comment]
Thank you Rich!

**Comment by yarnellr** [comment]
Happy to help! Have you published any research that utilizes this project or on any similar topics?

**Comment by giacomoboldini** [comment]
No, there hasn't been any publication related to this project or similar topics. We completed this project as part of the final exam for the Embedded Systems course at the University of Parma, and we developed two brief presentations for it (available in the repository's root). Additionally, we haven't undertaken any further initiatives on topics related to hardware design at the moment.
